project_name: rustbot
before:
  hooks:
    - go mod download
    - go mod tidy
    - docker login --u booleanismaybe -p {{ .Env.DOCKERHUB_TOKEN }}
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - amd64
    binary: "{{.ProjectName}}"
archives:
  - replacements:
      arm: rpi
      amd64: x86_64
dockers:
  - 
    goos: linux
    goarch: arm
    binaries:
      - "{{ .ProjectName }}"
    dockerfile: Dockerfile
    image_templates:
      - "booleanismaybe/{{.ProjectName}}:{{ .Tag }}"
      - "booleanismaybe/{{.ProjectName}}:latest"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
