before:
  hooks:
    - go mod download
    - make build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
archives:
  - replacements:
      arm: rpi
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
