before:
  hooks:
    - go mod download
    - make build
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
      - amd64
archives:
  - replacements:
      arm: rpi
dockers:
  -
    goos: linux
    goarch: arm 
    image_templates:
    - "booleanismaybe/rustbot:latest"
    - "booleanismaybe/rustbot:{{ .Tag }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
